-- Active: 1764232254939@@localhost@3306@lumya_dev
-- Generated by Mocodo 4.3.2 (modifié)
CREATE TABLE IF NOT EXISTS utilisateur (
  idUser         INT NOT NULL AUTO_INCREMENT,
  pseudo         VARCHAR(100),
  email          VARCHAR(150),
  motDePasseHash VARCHAR(255),
  dateNaissance  DATE,
  typeRole       VARCHAR(20),
  nom            VARCHAR(100),
  prenom         VARCHAR(100),
  bio            TEXT,
  pdp            VARCHAR(255),
  dateCreation   DATETIME DEFAULT CURRENT_TIMESTAMP ,
  suivi          INT,
  PRIMARY KEY (idUser),
  CHECK (dateNaissance <= DATE_SUB(dateCreation, INTERVAL 13 YEAR))
);



CREATE TABLE video (
  PRIMARY KEY (idVideo),
  idVideo          INT NOT NULL AUTO_INCREMENT, 
  titre            VARCHAR(255),
  urlVideo         VARCHAR(500),
  datePublication  DATETIME,
  nbVues           INT,
  statutModeration INT,
  tags             JSON,
  idUser           INT,
  FOREIGN KEY (idUser) REFERENCES utilisateur(idUser)
);

CREATE TABLE abonnement (
  PRIMARY KEY (idAbo),
  idAbo          INT NOT NULL AUTO_INCREMENT,
  typeAbo        INT,
  dateDebut      DATETIME,
  dateFin        DATETIME,
  statutPaiement INT,
  idUser         INT,
  FOREIGN KEY (idUser) REFERENCES utilisateur(idUser)
);

CREATE TABLE commentaire (
  PRIMARY KEY (idCommentaire),
  idCommentaire      INT NOT NULL AUTO_INCREMENT,
  contenuCommentaire TEXT,
  datePost           DATETIME DEFAULT CURRENT_TIMESTAMP,
  idVideo            INT,
  idUser             INT,
  FOREIGN KEY (idVideo) REFERENCES video(idVideo),
  FOREIGN KEY (idUser)  REFERENCES utilisateur(idUser)
);

CREATE TABLE humeur (
  PRIMARY KEY (idHumeur),
  idHumeur  INT NOT NULL AUTO_INCREMENT,
  dateSuivi DATETIME DEFAULT CURRENT_TIMESTAMP,
  humeurs   ENUM('joie', 'tristesse', 'colere', 'anxiete', 'stresse', 'fatigue'),
  idUser    INT,
  FOREIGN KEY (idUser) REFERENCES utilisateur(idUser)
);

CREATE TABLE likes (
  idLike        INT NOT NULL AUTO_INCREMENT,
  idUser        INT,
  idVideo       INT,
  idCommentaire INT,
  PRIMARY KEY (idLike),
  FOREIGN KEY (idUser)        REFERENCES utilisateur(idUser),
  FOREIGN KEY (idVideo)       REFERENCES video(idVideo),
  FOREIGN KEY (idCommentaire) REFERENCES commentaire(idCommentaire)
);

CREATE TABLE quiz (
  PRIMARY KEY (idQuiz),
  idQuiz      INT NOT NULL AUTO_INCREMENT,
  titre       VARCHAR(255),
  description TEXT
);

CREATE TABLE theme (
  PRIMARY KEY (idTheme),
  idTheme INT NOT NULL AUTO_INCREMENT,
  libelle VARCHAR(100)
);

CREATE TABLE passer (
  PRIMARY KEY (idUser, idQuiz),
  idUser         INT NOT NULL,
  idQuiz         INT NOT NULL,
  scoreObtenu    INT,
  datePassage    DATE,
  recommandation VARCHAR(255),
  FOREIGN KEY (idUser) REFERENCES utilisateur(idUser),
  FOREIGN KEY (idQuiz) REFERENCES quiz(idQuiz)
);

CREATE TABLE traiter (
  PRIMARY KEY (idTheme, idVideo),
  idTheme INT NOT NULL,
  idVideo INT NOT NULL,
  FOREIGN KEY (idTheme) REFERENCES theme(idTheme),
  FOREIGN KEY (idVideo) REFERENCES video(idVideo)
);
CREATE TABLE preferer (
  idUser  INT NOT NULL,
  idTheme INT NOT NULL,
  PRIMARY KEY (idUser, idTheme),
  FOREIGN KEY (idUser)  REFERENCES utilisateur(idUser),
  FOREIGN KEY (idTheme) REFERENCES theme(idTheme)
);