-- Generated by Mocodo 4.3.2 (modifié)

CREATE TABLE utilisateur (
  PRIMARY KEY (idUser),
  idUser         INT NOT NULL,
  pseudo         VARCHAR(100),
  email          VARCHAR(150),
  motDePasseHash VARCHAR(255),
  dateNaissance  DATE,
  typeRole       VARCHAR(20),
  nom            VARCHAR(100),
  prenom         VARCHAR(100),
  bio            TEXT,
  pdp            VARCHAR(255),
  dateCreation   DATETIME,
  suivi          INT
);

CREATE TABLE video (
  PRIMARY KEY (idVideo),
  idVideo          INT NOT NULL,
  titre            VARCHAR(255),
  urlVideo         VARCHAR(500),
  datePublication  DATETIME,
  nbVues           INT,
  statutModeration INT,
  tags             JSON,
  idUser           INT,
  FOREIGN KEY (idUser) REFERENCES utilisateur(idUser)
);

CREATE TABLE abonnement (
  PRIMARY KEY (idAbo),
  idAbo          INT NOT NULL,
  typeAbo        INT,
  dateDebut      DATETIME,
  dateFin        DATETIME,
  statutPaiement INT,
  idUser         INT,
  FOREIGN KEY (idUser) REFERENCES utilisateur(idUser)
);

CREATE TABLE commentaire (
  PRIMARY KEY (idCommentaire),
  idCommentaire      INT NOT NULL,
  contenuCommentaire TEXT,
  datePost           DATETIME,
  idVideo            INT,
  idUser             INT,
  FOREIGN KEY (idVideo) REFERENCES video(idVideo),
  FOREIGN KEY (idUser)  REFERENCES utilisateur(idUser)
);

CREATE TABLE humeur (
  PRIMARY KEY (idHumeur),
  idHumeur  INT NOT NULL,
  dateSuivi DATETIME,
  humeurs   INT,
  idUser    INT,
  FOREIGN KEY (idUser) REFERENCES utilisateur(idUser)
);

CREATE TABLE `like` (
  PRIMARY KEY (idLike),
  idLike        INT NOT NULL,
  idUser        INT,
  idVideo       INT,
  idCommentaire INT,
  FOREIGN KEY (idUser)        REFERENCES utilisateur(idUser),
  FOREIGN KEY (idVideo)       REFERENCES video(idVideo),
  FOREIGN KEY (idCommentaire) REFERENCES commentaire(idCommentaire)
);

CREATE TABLE quiz (
  PRIMARY KEY (idQuiz),
  idQuiz      INT NOT NULL,
  titre       VARCHAR(255),
  description TEXT
);

CREATE TABLE theme (
  PRIMARY KEY (idTheme),
  idTheme INT NOT NULL,
  libelle VARCHAR(100)
);

CREATE TABLE passer (
  PRIMARY KEY (idUser, idQuiz),
  idUser         INT NOT NULL,
  idQuiz         INT NOT NULL,
  scoreObtenu    INT,
  datePassage    DATE,
  recommandation VARCHAR(255),
  FOREIGN KEY (idUser) REFERENCES utilisateur(idUser),
  FOREIGN KEY (idQuiz) REFERENCES quiz(idQuiz)
);

CREATE TABLE traiter (
  PRIMARY KEY (idTheme, idVideo),
  idTheme INT NOT NULL,
  idVideo INT NOT NULL,
  FOREIGN KEY (idTheme) REFERENCES theme(idTheme),
  FOREIGN KEY (idVideo) REFERENCES video(idVideo)
);